### ISSUE TITLE
Bug: npm start cannot work on Windows

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#100]
Currently `npm start` runs `NODE_ENV=development nodemon` but that only works on unix/mac.

Please look into a cross-platform way to specify env variables, if one exists or a way to vary the script based on platform.

**Comment by vegetabill** [comment]
I have seen this used before but there might be other ways too: https://github.com/kentcdodds/cross-env

**Comment by vegetabill** [comment]
For a workaround on windows, you can just remove the `NODE_ENV=production` in package json command:

https://github.com/Techtonica/keyboard-shortcuts-practice/blob/12b8ae0acd99ae57ec81dba48cf89ddd77d04b06/package.json#L9

Please don't commit this if possible.

**Comment by paulrrdiaz** [comment]
Hey @vegetabill could I work on this?

**Comment by paulrrdiaz** [comment]
@alodahl done
