### ISSUE TITLE
[refactor] Replace repetitive if blocks with lookup

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#102]
The long if statements in this function are very repetitive. Please come up with a better way with less duplication to have this functionality work, such as a [lookup object](https://www.codereadability.com/replacing-if-statements-with-object-lookups/) or something else of your own choosing.

https://github.com/Techtonica/keyboard-shortcuts-practice/blob/1a642f3ce4a136ec3b325beec781f4ab97b18935/public/scripts/main.js#L143-L168

**Comment by nadyafebi** [comment]
Hi! I would love to work on this!

**Comment by Shraddha2104** [comment]
Assigned!

**Comment by vegetabill** [comment]
@nadyafebi thanks for fixing this!
