### ISSUE TITLE
[jQuery] Replace jQuery.text function with native function

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#104]
Currently we are using jQuery to update DOM contents but native browser functions exist to do this in a standard way so we don't need to rely on jQuery for this.

Example: 
https://github.com/Techtonica/keyboard-shortcuts-practice/blob/1a642f3ce4a136ec3b325beec781f4ab97b18935/public/scripts/main.js#L213

Search for all usages of the `.text(` function and replace with standard functionality.

[StackOverflow code example](https://stackoverflow.com/questions/1358810/how-do-i-change-the-text-of-a-span-element-using-javascript)

**Comment by linhhvo** [comment]
Hi @vegetabill, can I work on this?

**Comment by arpi-r** [comment]
Assigned!

**Comment by alodahl** [comment]
@linhhvo , if there is more jQuery you'd like to address, we can make an issue for you after you make a PR.
