### ISSUE TITLE
Replace use of jQuery add/remove class

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#111]
We are using jQuery DOM selectors to toggle classes and visibility in main.js but now all of those functionalities are part of the browser built-in functions.

For all usages of CSS class add and remove functions, e.g.

https://github.com/Techtonica/keyboard-shortcuts-practice/blob/27c54db1ce3187f2f40434fdabe677976d53cedc/public/scripts/main.js#L116

or 

https://github.com/Techtonica/keyboard-shortcuts-practice/blob/27c54db1ce3187f2f40434fdabe677976d53cedc/public/scripts/main.js#L131

Replace with the equivalent using the standard `document.querySelector` and [`Element.classList`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList)

**Comment by i-aryan** [comment]
Hey. I can get it done! Assign, please @vegetabill

**Comment by Shraddha2104** [comment]
Assigned!
