### ISSUE TITLE
Replace window resizing listener with CSS

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#121]
AFAIK listener can be almost certainly be replaced with a CSS rule that uses `100vh`. Please remove it and replace with that rule.

https://github.com/Techtonica/keyboard-shortcuts-practice/blob/21c1043d8e7275c151a6bb5d742987a3844b5f2e/public/scripts/main.js#L57-L60

**Comment by FrankyFrankFrank** [comment]
I can do this. Filled out the volunteer form and will come through with a PR very shortly.

**Comment by FrankyFrankFrank** [comment]
#124
