### ISSUE TITLE
Show Hint. After switch between questions, some keys still highlighted.

### ISSUE THREAD

**Issue by Karska-dev** [Techtonica/keyboard-shortcuts-practice#138]
When the user switches between questions with turned on hints, some keys remain highlighted. 

**Prerequisites**: application is opened, show hint is turned off.
**Steps to reproduce**:
1. Switch to the question: How do you go to the beginning of the line you are currently typing on? (shell shortcut)
2. Turn on 'Show hint' -> 'control' and 'a' keys are highlighted.
3. Switch to the previous question("How do you switch to the next most recently used window of the front app?")

**Actual result**: You see four keys highlighted. (screenshot attached) 
Turn off Show Hint -> 'Control' key still highlighted.

**Expected result**: Only '~'. 'Shift' and 'Command' should be highlighted. 

![Screen Shot 2020-10-08 at 3 26 55 PM](https://user-images.githubusercontent.com/4979096/95519858-ddfdf400-097a-11eb-8d90-1baa9a9fd04b.png)

**Comment by Karska-dev** [comment]
@alodahl, @vegetabill  If you find this issue relevant, I would be glad to fix it.

**Comment by vegetabill** [comment]
@Karska-dev thanks for reporting this! I noticed it when testing your PR. Please do fix it if you can. I'm assigning it to you now.
