### ISSUE TITLE
Prevent default fn and command commands.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/keyboard-shortcuts-practice#14]
Maybe using this? https://www.w3schools.com/jsref/event_preventdefault.asp

**Comment by vegetabill** [comment]
@MichelleGlauser this can be frustrating for the user, even in a keyboard shortcut quiz. Is there a specific combo that is causing issue? Perhaps we can blacklist a few of those instead.

**Comment by vegetabill** [comment]
merged into #29
