### ISSUE TITLE
Use a keycode JS library to handle keypress-related details

### ISSUE THREAD

**Issue by heyellieday** [Techtonica/keyboard-shortcuts-practice#15]
To be able to focus on the app's features, it makes sense to use a library like Keypress (https://dmauro.github.io/Keypress/) or Keymaster (https://github.com/madrobby/keymaster) that can run callback functions when key events happen.

**Comment by vegetabill** [comment]
I see that keymaster was checked in to the repo. Is it currently being used? Is someone working on this issue? If not, I can try to work on it.

**Comment by vegetabill** [comment]
Unless we're seeing bugs that a library would solve, I'd suggest skipping this for now.
