### ISSUE TITLE
Build JSON file with all keyboard shortcuts in the proper "schema"

### ISSUE THREAD

**Issue by heyellieday** [Techtonica/keyboard-shortcuts-practice#16]
*This issue is a WIP* (work in progress)

In order to have a in memory "database" to read keyboard shortcuts from, there will need to be a data source to pull in seed data (in this case, the keyboard shortcuts). For simplicity, it can be stored in a JSON file that can be read from the JS app and loaded into whatever in-memory data store is used.

Additionally, each keyboard shortcut object found in the JSON must conform to a standardized schema.

For now, that would mean each object must look like this:
```json
{
  "title": "paste",
 "description": "This is how you paste text that is in your clipboard",
 "interactions": ["key-cmd", "key-v"],  //each element is the string-based id of a key (or click) definition,
 "importance": 100 // importance of knowing shortcut in a scale of 0-100 where 100 is as important as can be. multiple shortcuts can share the same values
}
```

Additionally, keys and/or clicks (or other interactions) should be defined in an "interactions" collection with each element having a type key of "key" or "mouse-action". that collection should look like: 

```json
{
  "interactions": {
    "key-cmd": {
       "type": "key",
      "value": "cmd"
    }
  }
}
```

**Comment by vegetabill** [comment]
Don't think is needed anymore. The app is already showing a set of questions from a json file. If we want a specific schema improvement, we can open a ticket with the details.
