### ISSUE TITLE
Add a pause button

### ISSUE THREAD

**Issue by deeptiGarg** [Techtonica/keyboard-shortcuts-practice#21]
Add a pause button before a new prompt is shown (in place of the Next button). 

Pause should keep the user on the same question. Once Paused, Pause button should change to Resume button. Once Resumed, display the next question.

If not Paused, then the next question is displayed automatically after 2-3 seconds.

**Comment by deeptiGarg** [comment]
Guess we don't need this now. @Michelle plz correct me if I'm wrong.

**Comment by vegetabill** [comment]
Based on IRL conversation tonight, for the MVP we just want to auto-advance through the questions and there is no back since the user already got the question right. Closing this.
