### ISSUE TITLE
Highlight/accept the Command, Option, and Shift buttons on the right if the supporting keys are typed with the right hand.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/keyboard-shortcuts-practice#23]
For example, the Command button on the right should be used for copying, cutting, and pasting because C, X, and V are on the left of the keyboard and pressed with the left hand.

**Comment by vegetabill** [comment]
@MichelleGlauser is this MVP? Feels a little bit like a user preference is why I ask (one-handed always left, two-handed, etc). Or is it safe to assume everyone will want to learn and practice the same way?

(I must not be a good typist because I always use the left ones.)

**Comment by alodahl** [comment]
Closing since this was moved to "Done".
