### ISSUE TITLE
Keys "stick" on when switching tabs

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#25]
If you use Cmd+Alt+Left/Right to change browser tabs, the Cmd key gets stuck orange on even when it's not pressed. Ideally we should reset keys when returning.

Alternatively we may not need to do this is we do #29 but that might not be a great UX.

To get started, follow the instructions in https://github.com/Techtonica/keyboard-shortcuts-practice/blob/backend/CONTRIBUTING.md

**Comment by ananyakaushik** [comment]
Hi @vegetabill would you be able to provide more details, if this issue is still open? I wasn't able to reproduce this on Chrome or Firefox, and Safari seems to use a different shortcut

**Comment by vegetabill** [comment]
@ananyakaushik thanks for testing it. It must have been fixed in the interim by some other change. Sorry! Closing as fixed.

**Comment by vegetabill** [comment]
Oh not some random change, it was linked above by the banana person: https://github.com/Techtonica/keyboard-shortcuts-practice/pull/38/commits/032e29ce8ae4785cde93d4ba145ec7196c23d3a2 as part of #38
