### ISSUE TITLE
Add support for shortcuts with the Fn key

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#29]
This ticket is to allow shortcuts to be specified that require the `fn` key on Mac.

For example, F2 in VSCode renames a symbol, which is a useful tool. Add this shortcut to the shortcuts.json and test to see if it will work.

Ideally, we would like to highlight the actual `fn` key on the displayed keyboard but that may or may not be possible. Please look into the link below and do your own search to see if that is possible.

To get started, follow the instructions in https://github.com/Techtonica/keyboard-shortcuts-practice/blob/backend/CONTRIBUTING.md

_Note: Originally forked from #13 and #14. Command support was already implemented._

**Comment by lindes** [comment]
Note that pressing of the fn key by itself is probably not detectable from the browser, though keys pressed while holding it _may_ be detectable, depending on the key.

For more information, see: https://stackoverflow.com/questions/49945785/detect-fn-key-with-js

And/or experiment with: http://keycode.info/ (referenced from one of the answers.)

**Comment by Karska-dev** [comment]
@alodahl I would like to help you with this one. Could you please assign it?
