### ISSUE TITLE
Come up with list of commands for program to test.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/keyboard-shortcuts-practice#3]

**Comment by JonRojas** [comment]
[Basic Mac Keyboard Shortcuts](https://support.apple.com/en-us/HT201236)

| Shortcut                | Description                                                                                                                | 
|-------------------------|----------------------------------------------------------------------------------------------------------------------------| 
| Command-X               | Cut the selected item and copy it to the Clipboard.                                                                        | 
| Command-C               | Copy the selected item to the Clipboard.                                                                                   | 
| Command-V               | Paste the contents of the Clipboard into the current document or app.                                                      | 
| Command-Z               | Undo the previous command.                                                                                                 | 
| Command-Shift-Z         | Redo, reversing the undo command.                                                                                          | 
| Command-A               | Select All items.                                                                                                          | 
| Command-F               | Find items in a document or open a Find window.                                                                            | 
| Command-G               | Find Again: Find the next occurrence of the item previously found. To find the previous occurrence, press Command-Shift-G. | 
| Command-H               | Hide the windows of the front app.                                                                                         | 
| Command-Option-H        | View the front app but hide all other apps                                                                                 | 
| Command-M               | Minimize the front window to the Dock.                                                                                     | 
| Command-Option-M        | Minimize all windows of the front app.                                                                                     | 
| Command-N               | New: Open a new document or window.                                                                                        | 
| Command-O               | Open the selected item, or open a dialog to select a file to open.                                                         | 
| Command-P               | Print the current document.                                                                                                | 
| Command-S               | Save the current document.                                                                                                 | 
| Command-W               | Close the front window.                                                                                                    | 
| Command-Option-W        | Close all windows of the app                                                                                               | 
| Command-Q               | Quit the app.                                                                                                              | 
| Option-Command-Esc      | Force Quit: Choose an app to force quit.                                                                                   | 
| Command–Space bar       | Spotlight: Show or hide the Spotlight search field.                                                                        | 
| Command-Tab             | Switch apps: Switch to the next most recently used app among your open apps.                                               | 
| Shift-Command-Tilde (~) | Switch windows: Switch to the next most recently used window of the front app.                                             | 
| Shift-Command-3         | Screenshot: Take a screenshot of the entire screen.                                                                        | 
| Command-Comma (,)       | Preferences: Open preferences for the front app.                                                                           |

**Comment by JonRojas** [comment]
Great resource: https://github.com/0nn0/terminal-mac-cheatsheet

| Key/Command | Description                                                                                                                                       | 
|-------------|---------------------------------------------------------------------------------------------------------------------------------------------------| 
| Ctrl + A    | Go to the beginning of the line you are currently typing on. This also works for most text input fields system wide. Netbeans being one exception | 
| Ctrl + E    | Go to the end of the line you are currently typing on. This also works for most text input fields system wide. Netbeans being one exception       | 
| Ctrl + Q    | Clears everything on current line                                                                                                                 | 
| Ctrl + L    | Clears the Screen                                                                                                                                 | 
| Cmd + K     | Clears the Screen                                                                                                                                 | 
| Ctrl + U    | Cut everything backwards to beginning of line                                                                                                     | 
| Ctrl + K    | Cut everything forward to end of line                                                                                                             | 
| Ctrl + W    | Cut one word backwards using white space as delimiter                                                                                             | 
| Ctrl + Y    | Paste whatever was cut by the last cut command                                                                                                    | 
| Ctrl + H    | Same as backspace                                                                                                                                 | 
| Ctrl + C    | Kill whatever you are running                                                                                                                     | 
| Ctrl + D    | Exit the current shell when no process is running, or send EOF to a the running process                                                           | 
| Ctrl + Z    | Puts whatever you are running into a suspended background process. fg restores it.                                                                | 
| Ctrl + _    | Undo the last command. (Underscore. So it's actually Ctrl + Shift + minus)                                                                        | 
| Ctrl + T    | Swap the last two characters before the cursor                                                                                                    | 
| Ctrl + F    | Move cursor one character forward                                                                                                                 | 
| Ctrl + B    | Move cursor one character backward                                                                                                                | 
| Option + →  | Move cursor one word forward                                                                                                                      | 
| Option + ←  | Move cursor one word backward                                                                                                                     | 
| Esc + T     | Swap the last two words before the cursor                                                                                                         | 
| Tab         | Auto-complete files and folder names                                                                                                              |

**Comment by JonRojas** [comment]
Add question/answer structure around keyboard shortcuts.

**Comment by deeptiGarg** [comment]
Added a Shortcuts.txt file in the gh-pages branch. You can add shortcuts in it each as the below format - 

Key1-Key2-Key3 How do you do Action1?
Key1-Key2-Key4 How do you do Action2?

Something like this.

**Comment by MichelleGlauser** [comment]
What do we do about commands that still require a click, like Option-Click-Notification menu to disable notifications?

**Comment by vegetabill** [comment]
The click ones seem like an edge case.

This list seems all present in the json file. Let's open a new ticket if we want to add additional ones.
