### ISSUE TITLE
Add fun success event when the user has finished all the questions

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#30]
Currently when the user reaches the last question it just cycles back to the first one.

Let's help the user celebrate their accomplishment by showing a fun success message.

Also please add a button that will start the quiz over again if they want.

Try out the Keyboard Shortcut App:  https://techtonica.github.io/keyboard-shortcuts-practice/

**Comment by tonyd256** [comment]
Added confetti!! 08449b2c507881a748f8894f0012f46f1df3b2eb
