### ISSUE TITLE
[QA] Run through entire set of questions and create issues for any bugs seen

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#31]
Run through the tests on the latest Mac versions of:
* Chrome
* Firefox

**Comment by vegetabill** [comment]
Thanks @ewilliam for picking this up! One thing I forgot to mention originally is we should test on more than one browser. Chrome and Firefox on Mac OSX would be a good start but I'm not sure if @MichelleGlauser would have any additional suggestions based on the first cohort.

**Comment by deeptiGarg** [comment]
Issues List - 
https://paper.dropbox.com/doc/Bugs-0OEj9V1CmEyCcJlOUaOmD
