### ISSUE TITLE
caps-lock toggles only every other time you press it, losing sync with actual lock

### ISSUE THREAD

**Issue by lindes** [Techtonica/keyboard-shortcuts-practice#34]
At least for me, pressing caps-lock for the first time changed the keyboard view to reflect it being enabled, but then pressing it again didn't show it as disabled... pressing a third time did.  And now it seems to take every other press.

**Comment by lindes** [comment]
Note: After playing around a bit on [keycode.info](http://keycode.info/), it seems this may just be a case that only turning caps-lock on actually generates a keycode event that the browser can see, so this may be impossible to fix. :-/

**Comment by ashley-g** [comment]
I'd like to work on figuring this out!

**Comment by arpi-r** [comment]
Assigned!
