### ISSUE TITLE
Create an expert view that does not show blue hints until requested

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/keyboard-shortcuts-practice#4]
Currently the blue hint keys are always shown. We'd like a toggle so you can hide the hints so users can test their expertise.

Design a toggle UI and implement it to allow the user to show or hide hints.

**Comment by MichelleGlauser** [comment]
This is not needed for the MVP.

**Comment by vegetabill** [comment]
Right now they are always highlighted even before the student gets it wrong. Is this ticket meant to be like a "hint" feature?

**Comment by vegetabill** [comment]
@MichelleGlauser should there be a mode without the keys shown? Right now the keys are always shown.

**Comment by belebull** [comment]
I'd be happy to work on this as well!

**Comment by masbagal** [comment]
Hi, I'd be willing to help on this issue

**Comment by alodahl** [comment]
Fixed in #127
