### ISSUE TITLE
GHC'19:  add persistence layer so users can log in and save progress

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#46]
Use our dedicated trello board for related issues: https://trello.com/invite/b/n0K4702v/bea90647f14eae2be2a1ac54e124d566/techtonica-keyboard-app-persistance-layer

**Comment by DuaneOBrien** [comment]
@alodahl I was chatting with someone at one of our Open Source Study halls, and I wanted to clarify this issue/requirement.

If the only reason for the persistence layer is to preserve user progress between sessions, switching from sessionStorage to localStorage as the mechanism for preserving progress would meet this requirement, with a couple of caveats.

* progress would be only saved within the context of a given browser. So, switching browsers or computers would mean that the user is starting over;
* clearing the browser cache would reset progress;

If this is sufficient for persisting progress, #55 should address the issue. If not, then could you say a little more about how you would like to save/persist progress?

**Comment by alodahl** [comment]
I moved all the issues to the GitHub Project board.  https://github.com/Techtonica/keyboard-shortcuts-practice/projects/4
