### ISSUE TITLE
Disambiguate between mac keyboard shortcuts and shell shortcuts

### ISSUE THREAD

**Issue by judytuna** [Techtonica/keyboard-shortcuts-practice#47]
I'd love to see some indication that the keyboard shortcut I'm on is for the mac operating system vs the shell.

Suggestion: add navigation between different sets of shortcuts, perhaps after we get shortcuts for more programs, #22

**Comment by alodahl** [comment]
Since the 'mvp' is mainly done, I created a new project board: 
 https://github.com/Techtonica/keyboard-shortcuts-practice/projects/4

**Comment by vegetabill** [comment]
I think for this we just need a new attribute in the JSON data and a visual indicator of your choosing.

**Comment by belebull** [comment]
Happy to help with this! Is there a preferred indicator for this (maybe a simple tag under the cheat sheet link)? I can also create some quick mockups

**Comment by alodahl** [comment]
Mockups would be great!  I'm sure there are mac and shell icons out there, but I assume you mean where to show them on the app UI.

**Comment by alodahl** [comment]
Or even a colored tag would work!

**Comment by belebull** [comment]
Maybe something like this 
<img width="1004" alt="Screen Shot 2020-10-01 at 12 50 57 PM" src="https://user-images.githubusercontent.com/10715618/94845091-cd7ed400-03e4-11eb-87e5-0aacc21443ac.png">
