### ISSUE TITLE
Fix keyboard zoom bug

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#57]
<img width="755" alt="Screen Shot 2019-12-03 at 2 33 07 PM" src="https://user-images.githubusercontent.com/16828218/70095736-5ddc6480-15da-11ea-81bc-da203e14367e.png">

Zoom at 110%, 90%, 80% in chrome. Did not find the bug in Firefox.

To get started, follow the instructions in https://github.com/Techtonica/keyboard-shortcuts-practice/blob/backend/CONTRIBUTING.md

Originally reported by @IngridGdesigns

**Comment by luciagirasoles** [comment]
I would like to help here
