### ISSUE TITLE
Create an env file and share securely.

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#63]
Create an env file and share securely.

1. Request Techtonica's login elephantsql.com database URL from Alina. She will email it to you.

1. Create a .env file with URL=<DB url/username/password> you received in the last step.

1. Create a .env.example file with the key and false value.  Make a PR to the `backend` branch.

1. Send  new .env to Alina.

1. Send a message to all Techtonica project teammates that you or Alina can email them the real values on request.

**Comment by vegetabill** [comment]
This should probably be done by a project admin and we shouldn't share the credentials unless someone is debugging a production bug that needs it.

For those who need a local dev databases, we should link to [Homebrew postgres setup](https://github.com/Techtonica/curriculum/blob/main/databases/installing-postgresql.md) or Heroku/ElephantSQL free hosted tiers.

**Comment by alodahl** [comment]
Ah, that’s a good idea. Would you be open to adding a section in contributing about how to create their own DB and connect it to the project? Or write an issue to have someone do that early on, as well as add links to it in related issues?

**Comment by alodahl** [comment]
Question: could we do something similar for Auth0?

**Comment by vegetabill** [comment]
@alodahl since we're using sequelize, it's possible to use sqlite locally so no one will need to setup anything. This seems ideal, especially for Open Source Day.

I opened a PR that does that, #91, so as long as contributors use the sequelize API for any DB access, it shouldn't matter that they're developing against postgres.

**Comment by vegetabill** [comment]
For Auth0, I'm trying to achieve the same thing but I'll need to re-familiarize myself with Auth0 to see what the options are.

**Comment by vegetabill** [comment]
Solution documented in #64 - we should not need a shareable .env
