### ISSUE TITLE
First GET request: /user/progress

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#66]
Add new GET endpoint for the path `/user/progress`

This endpoint should return the following hardcoded response (since we don't yet know who the user is or their saved progress).

```json
{ 
  "userId": null,
  "currentQuestionNumber": 1
}
```

Once the main.js loads, add an AJAX call (using `fetch`, not jQuery) to the above endpoint and set the current question to the returned `currentQuestionNumber`

**Comment by marcobarrera** [comment]
May I work on this issue?

**Comment by alodahl** [comment]
Hi @marcobarrera, I'm actually saving these issues for a Grace Hopper Open Source Day team event next month.  However, we need lots of help here right away --> https://github.com/Techtonica/curriculum/projects/2

**Comment by swarna-gopalan** [comment]
Not sure I follow the instructions but I can take a look at it with some guidance as part of GraceHopperOSD

**Comment by Sangvi98** [comment]
Hi! Is this issue still open? I commented on another one that needs other issues to be resolved first and I'd like to work on this in the meantime.

**Comment by vegetabill** [comment]
I pinged the assignee in slack to see if they're actively working on it. If not, we can unassign.

**Comment by vegetabill** [comment]
Spoke to assignee in slack and they haven't had a chance to work on this so throwing back in the pool for now since other issues depend on this.

**Comment by ayushjain94** [comment]
@vegetabill I would like to take this one.

**Comment by Shraddha2104** [comment]
Assigned!

**Comment by vegetabill** [comment]
Since we never merged this and we know have auth, this will just be superseded by #77
