### ISSUE TITLE
Save answer POST request

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#67]
This depends on #72 so work on that first if you're interested and it isn't already assigned.

Add a new `POST` endpoint for the route: `/user/answers/question/{questionNumber}`

In the body of the request, include the necessary attributes (see #72) to save.

(Until auth is implemented, you can use `guest` as the user_id. Just make sure the record exists so the foreign key constraint isn't violated.)

In the main.js browser JavaScript, please submit an AJAX request (using `fetch`) to the above endpoint for any correct answer from the user. We can ignore incorrect answers for now.

This data will be retrieved in #96 if you're interested in working on that part.

**Comment by josselineperdomo** [comment]
I would like to choose this issue.

**Comment by vegetabill** [comment]
@josselineperdomo I've assigned you so you can get started but keep in mind to get this fully working, you'll need #72 to be merged so just keep that in mind 😃

**Comment by josselineperdomo** [comment]
I saw that the #72 was merged so I am finishing this issue, I am going create the PR soon :)
