### ISSUE TITLE
First DELETE request

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#68]
First DELETE request

1. Create a working basic DELETE request for user: { username, id } based on the project's existing DB and ORM.

2. Add your endpoint and example request and response in the ReadMe.

Request the project .env from teammates.

**Comment by vegetabill** [comment]
@alodahl not sure what we need this DELETE for so I demoted it. If I misunderstood, we can put it back. With Auth0 I don't know how to unregister an account and even if we do, most people don't explicitly close their inactive accounts.

**Comment by MariaKhantech** [comment]
I would like to do this if it is still available.

**Comment by Shraddha2104** [comment]
I think it's closed for now, try to pick another one!

**Comment by alodahl** [comment]
Hi @MariaKhantech , we realized this one wasn't needed so we closed it.  Try one of these: https://github.com/Techtonica/keyboard-shortcuts-practice/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+label%3A%22help+wanted%22+no%3Aassignee
