### ISSUE TITLE
First PUT request

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#69]
First PUT request

For this task, you will be adding a column/field to the user: savepoint.
1. Create a working basic PUT request for user: { username, id, savepoint } based on the project's existing DB and ORM.
2. Add your endpoint and example request and response in the readme.

Dependencies:
- Savepoint strategy must be documented.
- Ask Techtonica teammates for the project .env .

Not required: 
Actual saving functionality will be addressed in a future issue.  The current issue only focuses on the functioning PUT request and the savepoint type.

**Comment by itsdell** [comment]
Hello, can I take this one?

**Comment by alodahl** [comment]
Hi @itsdell, I'm actually saving these issues for a Grace Hopper Open Source Day team event next month. However, we need lots of help here right away --> https://github.com/Techtonica/curriculum/projects/2

**Comment by vegetabill** [comment]
Functionality now handled by 
Save answer POST request #67
