### ISSUE TITLE
Write user's progress PUT request

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#70]
User story:
As a user, I want to have my savepoint automatically recorded as I progress. No "save" button should be required.
- The plan for creating a savepoint should be in the readme.

- Add your endpoint and example request and response in the readme, or update if it overrides an existing endpoint.

Dependencies:
P1(blue) & P2(green) Issues

**Comment by vegetabill** [comment]
Handled by:
Save answer POST request #67
