### ISSUE TITLE
Add UserAnswers model and DB schema to orm.js

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#72]
A a new model in orm.js based on this definition

#### `user_answers` table / UserAnswers model

All of these columns are `NOT NULL` unless otherwise specified.

- `id`: primary key / integer sequence
- `user_id`: string (foreign key to `users.id`)
- `question_number`: integer
- `is_correct`: [boolean](https://sequelize.org/master/manual/model-basics.html#boolean)
-  `elapsed_time_ms`: integer
- `created_at` : timestamp (we don't need updated_at since this is immutable. this name can be [configured in the sequelize model](https://sequelize.org/master/manual/model-basics.html#timestamps) as we don't want the default camel case name)

Please use the [sequelize docs](https://sequelize.org/master/)

**Comment by ambikasadhu1101** [comment]
I'd like to work on this
