### ISSUE TITLE
Integrate Auth0 middleware into the server

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#73]
You'll need to register your own free account with [Auth0](https://auth0.com/) to work on this issue.

- Create a new application in your Auth0 account
  - The type is *Regular Web Application*
- Follow the Auth0 tutorial for NodeJS / Express to integrate it into the app
  - Using the Auth0-endorsed express middleware, [express-openid-connect](https://www.npmjs.com/package/express-openid-connect)
- Auth0 will provide a test to tell if the auth is working correctly
- To help others set it up in their environment, add environment variable names to the `.env.example` file. Do not put any of your own account/app's values here.
- Only configure the middleware if the Auth0 environment variable names you chose are present. If not, assume the app is running in local dev mode and will not need Auth0 integration. Local auth will be implemented in #74 
- Please document in the README how someone can set up their own Auth0 (use links to official docs), such as copying the `.env.example` file 

If you need help with Express or Auth0, ping Bill in Slack.

**Comment by isabellberzsenyi** [comment]
I'd like to pick this task up!

**Comment by vegetabill** [comment]
Thanks @isabellberzsenyi I've assigned you! Lmk if you have any questions as you work on it
