### ISSUE TITLE
Create fake login/logout for local development

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#74]
Auth0 is being integrated as part of #73 but we don't want to force all contributors to configure Auth0 just to work on the app so we'll have a simple auth setup for local development.

Feel free to suggest a better way to do this. This just one possible way among many.

- This should be the default way the app works unless Auth0 is setup - which will be done in #73 
- Add the [cookie-session](https://www.npmjs.com/package/cookie-session) package or your preferred cookie library
  - If you haven't worked directly with cookies before, read this [background doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies)
- Implement a `GET /login` endpoint
  - It should set a cookie, `userId` which will just be the environment variable `USER` (your OS username) which has a lifetime of 1 hour
  - If no user record exists with that id, create it. Sequelize has a `findOrCreate` helper that makes this easy
  - The response to this endpoint should be a redirect to `/`
- Implement a `GET /logout` endpoint
  - It should unsets the cookie value
  - Response should be a redirect to `/`
- Update the `/user/progress` endpoint added in #66 so that the userId will be the logged-in user id if the cookie has the value set

If you have any question about cookies, Express, ping Bill D in Slack.

**Comment by rpytan** [comment]
I'm interested in working on this.

**Comment by MariaKhantech** [comment]
I am interested in working on this.

**Comment by vegetabill** [comment]
@rpytan I've assigned you but feel free free to pair with @MariaKhantech  if you'd like!

**Comment by vegetabill** [comment]
Hi @rpytan not sure how much progress you made on OSD or if you anticipate having time to finish it. If not, perhaps @MariaKhantech might be interested in working on it or we can also just unassign it for someone else to pick up. Either way is fine. Just let us know. Thanks!

**Comment by y-martinez** [comment]
Hi! @vegetabill I would like to work on this issue if the PR has not yet been created, I can still wait for the response from the people who are assigned to it.

**Comment by y-martinez** [comment]
Ohh I had not seen that you solved it

**Comment by rpytan** [comment]
Hi Bill,
Sorry for the late reply. Unfortunately, I was not able to make much
progress during OSD and I don't think I will have time to continue with it.

**Comment by vegetabill** [comment]
Thanks for the offer, @y-martinez. Hopefully you see another issue that interests you. We have a bunch. If you need help finding one, please let me know.

**Comment by vegetabill** [comment]
Since I worked on a spike of Auth0/dev auth while we were creating the issues, I am adapting that spike code for a PR that will be ready soon. Assigning to me in the meantime.
