### ISSUE TITLE
Add Login/Logout button to the UI

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#75]
Note: make pull requests to  techtonica/keyboard-shortcuts-practice's 'backend' branch.

Design and implement a Login and Logout button. They should take the user to `/login` and `/logout`, respectively but those pages don't currently exist yet and will just show a 404. 

Please design with either a navbar or just a button on the top of the page. It's up to you. There is currently no toolbar or header to the UI.

**Comment by Sgeis18** [comment]
Hi, I would like to pick up this issue.

**Comment by astha01** [comment]
Hi, I would also like to work on it

**Comment by vegetabill** [comment]
@Sgeis18 I've assigned you but feel free to ping @astha01 if you'd like to pair!

**Comment by Sgeis18** [comment]
Sure - @astha01 would you like to work together?

**Comment by nayelimdejesus** [comment]
I can work on this

**Comment by alodahl** [comment]
Hi @nayelimdejesus this is already in progress.  check out the top issues in the ToDo column here: https://github.com/Techtonica/keyboard-shortcuts-practice/projects/4

**Comment by vegetabill** [comment]
Closed in favor of #76 adding the UI and state.
