### ISSUE TITLE
Logging in will return user to the last question they were on

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#77]
This is blocked by #66 and is to correctly implement the `/user/progress` placeholder endpoint.

Until #74 is implemented, you will need to set up Auth0 in order to know how is logged in.

We should lookup the most recently added answer data for a user and return its question number + 1 as the current number. We should use this as the authoritative source of the current question number, not local storage as it is now.

**Comment by MariaKhantech** [comment]
I would like to take this if it has not been assigned yet.

**Comment by vegetabill** [comment]
While integrating all the piecemeal changes, I implemented this while doing #142 but since @MariaKhantech was still working on webpack, hopefully that's no problem.
