### ISSUE TITLE
Add Auth0 authentication to sign in button

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#78]
Add Auth0 authentication to sign in button.

**Comment by vegetabill** [comment]
The middleware will handle this so we don't need to do anything special. Closing.

**Comment by alodahl** [comment]
@vegetabill please push back on this if I'm wrong, but I think this is still needed if theres a userless mode.

**Comment by alodahl** [comment]
Or is this a duplicate of #76 ?

**Comment by alodahl** [comment]
Oh I see. This is a duplicate of #76.
