### ISSUE TITLE
Verify login/logged in button functions (UI)

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#79]
Now that we have Auth0 integrated in #73 and a simple auth for local development in #74, let's make sure the login/already logged in button shows the correct state. The button should show 'log-in' when there is no user yet, and switch to 'logged in' when the user has been authenticated.

Ensure that the logged in state:

- is visible once the user logs in
- toggles from log-in to logged in in the appropriate states
- feel free to use language or cues other than 'logged in' - we just need to make it clear that their progress is now being saved.

Dependencies:

- Log-in UI with toggle function already exists

**Comment by vegetabill** [comment]
@alodahl is this just an accidental dupe of #76 ? I may have created it when triaging issues the day before OSD.

**Comment by alodahl** [comment]
It might be, @vegetabill !

**Comment by alodahl** [comment]
Unless one is issue is for UI and one is for functionality.

**Comment by vegetabill** [comment]
Hmm, I think #75 is the UI part so I'm going to close this as a dupe of #76
