### ISSUE TITLE
Ensure correct user data is being fetched when a user logs in.

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#81]
Ensure correct user data is being fetched when a user logs in.

**Comment by astha01** [comment]
Hi would like to work on it

**Comment by astha01** [comment]
Thanks ! @danisyellis

**Comment by vegetabill** [comment]
@alodahl this seems like a dupe of #77 to me. Is there some other data that we are expecting to need upon login?

**Comment by alodahl** [comment]
I think you're more tuned-in to that at this point...  If you think that's all, please close the issue 🙂

**Comment by vegetabill** [comment]
Closing as dupe of #77. If we need more user state upon login, we can open another issue.
