### ISSUE TITLE
Add 'defer' attributes to script tags in index.ejs

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#92]
Having all the external JavaScript loaded before the HTML means that on a slow connection the page will not display until all of the resources are downloaded, but we don't really need the JavaScript to be able to render the keyboard, only to start the welcome animation.

For each of the `<script>` tags at the top of the HTML body, please add a `defer` attribute to them.

After making this change, please test that the page still works correctly. You can simulate slow loading times to help with [Chrome Dev Tools throttling](https://helpdeskgeek.com/networking/simulate-slow-internet-connection-testing/).

For more background context, see [async vs defer](https://www.growingwiththeweb.com/2014/02/async-vs-defer-attributes.html).

**Comment by swarna-gopalan** [comment]
@vegetabill - I can take this one as part of GraceHopperOSD

**Comment by racheltl** [comment]
I'm interested in working on this as well!
