### ISSUE TITLE
Add a nice favicon

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#93]
Find a free to use icon and make it our favicon

This site has a lot of free ones - https://www.flaticon.com/ as long as we properly attribute in our footer.

**Comment by nidhishs** [comment]
Hey, I have some experience doing graphic design. If you want, I can design a custom favicon for you.

**Comment by alodahl** [comment]
Hi @nidhishs,  don’t go overboard for us, but that sounds amazing!

**Comment by nidhishs** [comment]
> Hi @nidhishs, don’t go overboard for us, but that sounds amazing!

Not a problem at all. Let me know what specifications you want, such as any colour schemes you want me to abide by, or any ideas you might have.

Also if you don't mind, it would be great if I could send the PR in October so it also get's counted for Hacktoberfest.

**Comment by alodahl** [comment]
Of course, let's count this for hacktoberfest!  

Check out our GitHub profile icon and Techtonica.org... our branding uses a certain shade of teal, and white.  Our only mascot so far has been the Golden Gate Bridge. @MichelleGlauser please jump in if there's more to it than that.

**Comment by nidhishs** [comment]
Hey, I'm extremely for ghosting you guys for almost a week. Was busy with some assignments, but now I'm back :)

Considering you guys need a favicon, I figured having something as detailed as your mascot (the Golden Gate Bridge) inside a tiny favicon wouldn't look good. So I designed this icon with the ⌘ icon since the concerned website is for keyboard practice. This is the first idea that came to my mind, so please critique whatever you feel needs to be changed. I also designed one with your brand name, however it becomes also difficult to read on such a small scale. Let me know what you guys think and I'll try to cater to your needs. 
![techtonica](https://user-images.githubusercontent.com/55269918/94977174-e5a34000-0517-11eb-8c2e-8981d1f51d91.png)

**Comment by alodahl** [comment]
I love the first command key one!  😍  What do you think @vegetabill @MichelleGlauser ?

**Comment by nidhishs** [comment]
@alodahl If you like the first icon, should I make a PR for it?
I'll add the icon to images/favicon

**Comment by alodahl** [comment]
I'd like a few more Techtonica leaders to have a look this week before the final decision. Thanks @nidhishs !

**Comment by vegetabill** [comment]
Thanks for this contribution, @nidhishs 

+1 to @alodahl 's choice. I too like the top left one the best. What's your take, @MichelleGlauser ?

**Comment by alodahl** [comment]
Michelle's feedback:
"Hi Alina, maybe they could do something with a keyboard or a bunch of buttons?
Or we could just use the Techtonica favicon."

**Comment by alodahl** [comment]
She's also wondering how you would feel about removing the brackets from the command symbol one.

**Comment by nidhishs** [comment]
Thanks Alina for conveying the feedback
> "Hi Alina, maybe they could do something with a keyboard or a bunch of buttons?
Yes that was my initial thought, however the button on the keyboard would look too cluttered when shrunk to the size of a favicon. However, I will design it, and you can decide if it suits your taste.

> She's also wondering how you would feel about removing the brackets from the command symbol one.
Very much possible if you prefer it that way. I'll make the changes and share them here later today.

> Or we could just use the Techtonica favicon."
> She's referring to the favicon on this site: https://techtonica.org/
Yes the favicon on that site is certainly useable. Please let me know what you decide.

**Comment by nidhishs** [comment]
Removed the < > symbol.
![Artboard 10](https://user-images.githubusercontent.com/55269918/95267679-1a740780-0836-11eb-9c5c-5da7bcc54d5a.png)

Tried making a minimalist keyboard.
![Artboard 11](https://user-images.githubusercontent.com/55269918/95267694-219b1580-0836-11eb-8cb4-b3ff82bfdbdc.png)

Let me know what you think of these.

**Comment by alodahl** [comment]
I'll ask Michelle.  @nidhishs these are amazing 🤸🏼‍♀️

**Comment by nidhishs** [comment]
> I'll ask Michelle. @nidhishs these are amazing 🤸🏼‍♀️

Do we have any suggestions or are we good to make a PR? @alodahl

**Comment by alodahl** [comment]
Lets go with the keyboard!

**Comment by vegetabill** [comment]
Closed by #140
