### ISSUE TITLE
Setup webpack for the browser JavaScript

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#94]
Currently, the files in `public/scripts` are included one by one in script tags on our HTML pages. This makes it a little tricky for interdependencies between the files and for requiring external packages.

Ideally, we'd like to build a single bundle of JavaScript that combines any necessary dependencies that are available as NPM packages.

Please look into this and configure that for our project so that we can
- Live reload the JavaScript in development
- Build a minified asset for the production deploy

**Comment by MariaKhantech** [comment]
I would like to try this

**Comment by Shraddha2104** [comment]
Assigned!
