### ISSUE TITLE
Replace jQuery ajax with fetch

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#95]
For our API calls in `main.js` we're currently using jQuery's AJAX functions. These are outdated and use non-standard promises.

Let's migrate these to use `fetch`

**Comment by linhhvo** [comment]
Hi @vegetabill - I would like to work on this!

**Comment by linhhvo** [comment]
@alodahl Got it! I will check out other priority 1 or 2 issues.

**Comment by astha01** [comment]
Hi, Would like to work on this

**Comment by tilaprimera** [comment]
> 
> 
> Hi, Would like to work on this
Would you like to still work on it, I can have it assigned to you @astha01

**Comment by vegetabill** [comment]
@astha01 this is not blocked on anything. So feel free to start! Sorry for the confusing labels.

**Comment by alodahl** [comment]
already addressed in https://github.com/Techtonica/keyboard-shortcuts-practice/pull/109/
