### ISSUE TITLE
Add ability to retrieve timing history for a single question

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#96]
Currently, the timing history is stored in local storage. The code for it is in `history.js.` But after #67 we can retrieve this from the database instead.

- Add a new `GET` endpoint `/user/answers/question/{questionNumber}`
- Respond with 0-3 answer records if they exist (JSON shown below)
- Use this data to populate the existing timing boxes

```json
{
  "previousTimingMs": [53, 210, 303]
}
```
If there is no history, if they have never answered it before, include `[]` for the timings.

When showing a new question, make an AJAX call (using `fetch`, not jQuery) to this API endpoint and use the timing in the JSON to populate the existing UI. Feel free to modify history.js however you want. It no longer needs local storage.

**Comment by Sangvi98** [comment]
I'd like to be assigned to this issue!

**Comment by arpi-r** [comment]
Assigned!

**Comment by alodahl** [comment]
You can get started, but keep in mind to get this fully working, you'll need #67 to be merged so just keep that in mind 😃

**Comment by Sangvi98** [comment]
Just to make sure my understanding is correct, I can actually go ahead and work on this but to test whether I've implemented it correctly, I would need #67 to be resolved first?

**Comment by vegetabill** [comment]
@Sangvi98 you can't really do much with this until #67 is merged, unless you're comfortable creating a hardcoded API endpoint to return some test data. If you want more details on this, just lmk!

**Comment by vegetabill** [comment]
@Sangvi98 just FYI the backend model for this was merged so you can work on this as long as you're okay manually creating test data (since the real functionality to save the previous answers is waiting on #67)

**Comment by vegetabill** [comment]
The PR is #97

**Comment by Sangvi98** [comment]
Hi! I was having issue figuring out how to go about this, so I unassigned myself for now.

**Comment by josselineperdomo** [comment]
Hi! I would like work with this issue  :)

**Comment by vegetabill** [comment]
@josselineperdomo awesome! I assigned you. Lmk if you have any questions!
