### ISSUE TITLE
[jQuery] Replace CSS toggle class with built-in function

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/keyboard-shortcuts-practice#99]
We are using jQuery DOM selectors to toggle classes and visibility in main.js but now all of those functionalities are part of the browser built-in functions.

Replace all class toggles, e.g. `$('.letter').toggleClass('uppercase');` with the equivalent using the standard `document.querySelector` and [`Element.classList`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList)

**Comment by soxinmypocket** [comment]
I would like to work on this one

**Comment by y-martinez** [comment]
This issue is available?
